name: Azure Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: cxqa-webapp  # Replace with your Azure Web App name
        slot-name: 'production'      # Use 'production' for the main app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
